## H24081163 陳詠翰 B14081027 劉恩兆 H24081341 耿皓畇
這一份code的檔案為 problem 3、4 的程式碼

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# import package and load data

In [5]:
import pandas as pd
import numpy as np
income = pd.read_csv("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/income_evaluation.csv")
import scipy.io as sio    
mat = sio.loadmat('/content/drive/MyDrive/成大課程/巨量資料分析/HW5/arrhythmia.mat')
arrhy = pd.DataFrame(np.hstack((mat['X'], mat['y'])))
f = open("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/bank/bank-full.csv","r")
line = f.readline()
bank_column = line.split(";")
bank_column = [i.strip().strip('\n"') for i in bank_column]
print(bank_column)
bank_data_list =[]
for line in f.readlines():
    linetolist = line.split(";")
    linetolist = [i.strip('\n"') for i in linetolist]
    bank_data_list.append(linetolist)
f.close()
bank = pd.DataFrame(bank_data_list,columns = bank_column)
blastchar = pd.read_csv("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/WA_Fn-UseC_-Telco-Customer-Churn.csv")
htru = pd.read_csv("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/HTRU2/HTRU_2.csv",header=None)
kdd99 = pd.read_csv("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/kdd99/kddcup.data_10_percent_corrected",header=None)
shopper = pd.read_csv("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/online_shoppers_intention.csv")
f = open("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/biodeg.csv","r")
bio_list =[]
for line in f.readlines():
    linetolist = line.split(";")
    linetolist = [i.strip().strip('\"') for i in linetolist]
    bio_list.append(linetolist)
f.close()
bio = pd.DataFrame(bio_list,columns = range(len(bio_list[0])))
shrutime = pd.read_csv("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/Churn_Modelling.csv")

f = open("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/spambase/spambase.data","r")
'''
line = f.readline()
bio_column = line.split(";")
bio_column = [i.strip().strip('\"') for i in bio_column]
'''
#print(bank_column)
spam_list =[]
for line in f.readlines():
    linetolist = line.split(",")
    linetolist = [i.strip().strip('\"') for i in linetolist]
    spam_list.append(linetolist)
f.close()
spam = pd.DataFrame(spam_list,columns = range(len(spam_list[0])))
default = pd.read_csv("/content/drive/MyDrive/成大課程/巨量資料分析/HW5/Default.csv")
income_column = list(income.columns)
income_column = [i.strip()for i in income_column]
income.columns = income_column

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

# data preprocessing

In [6]:
income

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [7]:
income['income'].replace([' <=50K',' >50K'],[0,1],inplace = True)
income.rename(columns={"income": "y"},inplace = True)

In [8]:
arrhy.rename(columns={274: "y"},inplace = True)

In [9]:
arrhy

,0,1,2,3,4,5,6,7,8,9,...,265,266,267,268,269,270,271,272,273,y
0,75.0,0.0,190.0,80.0,91.0,193.0,371.0,174.0,121.0,-16.0,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,1.0
1,56.0,1.0,165.0,64.0,81.0,174.0,401.0,149.0,39.0,25.0,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,0.0
2,54.0,0.0,172.0,95.0,138.0,163.0,386.0,185.0,102.0,96.0,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,0.0
3,55.0,0.0,175.0,94.0,100.0,202.0,380.0,179.0,143.0,28.0,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,0.0
4,75.0,0.0,190.0,80.0,88.0,181.0,360.0,177.0,103.0,-16.0,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53.0,1.0,160.0,70.0,80.0,199.0,382.0,154.0,117.0,-37.0,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,0.0
448,37.0,0.0,190.0,85.0,100.0,137.0,361.0,201.0,73.0,86.0,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,0.0
449,36.0,0.0,166.0,68.0,108.0,176.0,365.0,194.0,116.0,-85.0,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,0.0
450,32.0,1.0,155.0,55.0,93.0,106.0,386.0,218.0,63.0,54.0,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,0.0
451,78.0,1.0,160.0,70.0,79.0,127.0,364.0,138.0,78.0,28.0,...,0.0,10.4,-1.8,0.0,0.0,0.5,1.6,21.3,32.8,0.0

In [10]:
bank['y'].replace(['no','yes'],[0,1],inplace = True)
bank

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,0
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,0
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,0
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,1
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,1
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,0
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,0

In [11]:
blastchar

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [12]:
blastchar.rename(columns={"Churn": "y"},inplace = True)
blastchar['y'].replace(['No','Yes'],[0,1],inplace = True)
blastchar.drop(['customerID'], axis=1,inplace=True)
blastchar

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,y
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,1
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,0

In [13]:
blastchar['y'].value_counts()

0    5174
1    1869
Name: y, dtype: int64

In [14]:
htru.rename(columns={8: "y"},inplace = True)
htru

,0,1,2,3,4,5,6,7,y
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
...,...,...,...,...,...,...,...,...,...
17893,136.429688,59.847421,-0.187846,-0.738123,1.296823,12.166062,15.450260,285.931022,0
17894,122.554688,49.485605,0.127978,0.323061,16.409699,44.626893,2.945244,8.297092,0
17895,119.335938,59.935939,0.159363,-0.743025,21.430602,58.872000,2.499517,4.595173,0
17896,114.507812,53.902400,0.201161,-0.024789,1.946488,13.381731,10.007967,134.238910,0
17897,57.062500,85.797340,1.406391,0.089520,188.306020,64.712562,-1.597527,1.429475,0

In [15]:
htru['y'].value_counts()

0    16259
1     1639
Name: y, dtype: int64

In [16]:
shopper

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [17]:
shopper.rename(columns={'Revenue': "y"},inplace = True)
shopper['y'].replace([False,True],[0,1],inplace = True)
shopper['Weekend'].replace([False,True],[0,1],inplace = True)
shopper

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,y
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,0,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,0,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,0,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,0,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,1,0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,1,0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,1,0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,0,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,1,0

In [18]:
shopper['y'].value_counts()

0    10422
1     1908
Name: y, dtype: int64

In [19]:
bio.rename(columns={41: "y"},inplace = True)
bio['y'].replace(["NRB","RB"],[0,1],inplace = True)
bio

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,y
0,3.919,2.6909,0,0,0,0,0,31.4,2,0,...,0,0,0,2.949,1.591,0,7.253,0,0,1
1,4.17,2.1144,0,0,0,0,0,30.8,1,1,...,0,0,0,3.315,1.967,0,7.257,0,0,1
2,3.932,3.2512,0,0,0,0,0,26.7,2,4,...,0,0,1,3.076,2.417,0,7.601,0,0,1
3,3,2.7098,0,0,0,0,0,20,0,2,...,0,0,1,3.046,5,0,6.69,0,0,1
4,4.236,3.3944,0,0,0,0,0,29.4,2,4,...,0,0,0,3.351,2.405,0,8.003,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,5.431,2.8955,0,0,0,2,0,32.1,4,1,...,0,6,1,3.573,2.242,1,8.088,0,0,0
1051,5.287,3.3732,0,0,9,0,0,35.3,0,9,...,0,3,0,3.787,3.083,3,9.278,0,0,0
1052,4.869,1.767,0,1,9,0,5,44.4,0,4,...,4,13,0,3.848,2.576,5,9.537,1,0,0
1053,5.158,1.6914,2,0,36,0,9,56.1,0,0,...,1,16,0,5.808,2.055,8,11.055,0,1,0
1054,5.076,2.6588,2,0,0,0,4,54.5,0,0,...,2,0,0,4.009,2.206,0,9.13,0,2,0

In [20]:
bio['y'].value_counts()

0    699
1    356
Name: y, dtype: int64

In [21]:
shrutime
shrutime.rename(columns={"Exited": "y"},inplace = True)
shrutime.drop(['Surname','RowNumber','CustomerId'], axis=1,inplace=True)
shrutime

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,y
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [22]:
shrutime['y'].value_counts()

0    7963
1    2037
Name: y, dtype: int64

In [23]:
spam.rename(columns={57: "y"},inplace = True)
spam

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,y
0,0,0.64,0.64,0,0.32,0,0,0,0,0,...,0,0,0,0.778,0,0,3.756,61,278,1
1,0.21,0.28,0.5,0,0.14,0.28,0.21,0.07,0,0.94,...,0,0.132,0,0.372,0.18,0.048,5.114,101,1028,1
2,0.06,0,0.71,0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0,0.276,0.184,0.01,9.821,485,2259,1
3,0,0,0,0,0.63,0,0.31,0.63,0.31,0.63,...,0,0.137,0,0.137,0,0,3.537,40,191,1
4,0,0,0,0,0.63,0,0.31,0.63,0.31,0.63,...,0,0.135,0,0.135,0,0,3.537,40,191,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0,0.62,0,0,0.31,0,0,0,0,...,0,0.232,0,0,0,0,1.142,3,88,0
4597,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.353,0,0,1.555,4,14,0
4598,0.3,0,0.3,0,0,0,0,0,0,0,...,0.102,0.718,0,0,0,0,1.404,6,118,0
4599,0.96,0,0,0,0.32,0,0,0,0,0,...,0,0.057,0,0,0,0,1.147,5,78,0
4600,0,0,0.65,0,0,0,0,0,0,0,...,0,0,0,0.125,0,0,1.25,5,40,0

In [24]:
spam['y'].value_counts()

0    2788
1    1813
Name: y, dtype: int64

In [25]:
default.rename(columns={"default.payment.next.month": "y"},inplace = True)
default.drop(['ID'], axis=1,inplace=True)
default

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,y
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,3,1,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,1,3,2,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,1,2,2,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,3,1,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,1,2,1,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [26]:
bio_copy = bio.copy()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
for col  in bio_copy.columns:
    scaler.fit(bio[[col]])
    bio_copy[['scale' + str(col)]] = scaler.transform(bio_copy[[col]])
bio_copy
bio

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,y
0,3.919,2.6909,0,0,0,0,0,31.4,2,0,...,0,0,0,2.949,1.591,0,7.253,0,0,1
1,4.17,2.1144,0,0,0,0,0,30.8,1,1,...,0,0,0,3.315,1.967,0,7.257,0,0,1
2,3.932,3.2512,0,0,0,0,0,26.7,2,4,...,0,0,1,3.076,2.417,0,7.601,0,0,1
3,3,2.7098,0,0,0,0,0,20,0,2,...,0,0,1,3.046,5,0,6.69,0,0,1
4,4.236,3.3944,0,0,0,0,0,29.4,2,4,...,0,0,0,3.351,2.405,0,8.003,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,5.431,2.8955,0,0,0,2,0,32.1,4,1,...,0,6,1,3.573,2.242,1,8.088,0,0,0
1051,5.287,3.3732,0,0,9,0,0,35.3,0,9,...,0,3,0,3.787,3.083,3,9.278,0,0,0
1052,4.869,1.767,0,1,9,0,5,44.4,0,4,...,4,13,0,3.848,2.576,5,9.537,1,0,0
1053,5.158,1.6914,2,0,36,0,9,56.1,0,0,...,1,16,0,5.808,2.055,8,11.055,0,1,0
1054,5.076,2.6588,2,0,0,0,4,54.5,0,0,...,2,0,0,4.009,2.206,0,9.13,0,2,0

In [27]:
income_con_col = []
income_cat_col = []
arrhy_con_col = []
arrhy_cat_col = []
bank_cat_col = ['job', 'marital' ,'contact','month','poutcome','default','housing','loan','education']
bankdropy = bank.drop(['y'],axis = 1)
bank_con_col = list(bankdropy.drop(bank_cat_col,axis=1).columns)
htru_con_col = []
htru_cat_col = []
blast_con_col = []
blast_cat_col = []
shopper_con_col = []
shopper_cat_col = []
bio_con_col = []
bio_cat_col = []
shrutime_con_col = []
shrutime_cat_col = []
spam_con_col = []
spam_cat_col = []
default_cat_col = ['SEX','EDUCATION','MARRIAGE','PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6']
defaultdropy = default.drop(['y'],axis = 1)
default_con_col = list(defaultdropy.drop(default_cat_col,axis=1).columns)

In [28]:
blastchar = blastchar[blastchar['TotalCharges']!=' ']
blastchar

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,y
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,1
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,0

In [29]:
bio= bio.apply(pd.to_numeric)
spam = spam.apply(pd.to_numeric)
blastchar[['TotalCharges']] = blastchar[['TotalCharges']].apply(pd.to_numeric)
bank[bank_con_col] = bank[bank_con_col].apply(pd.to_numeric)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [30]:
def con_cat(dataframe,con_list,cat_list):
    for i in dataframe.columns:
        if (i !='y'):
        #print(type(shopper[i][0]))
            if (type(dataframe[i][0])==str):   
                cat_list.append(i)
            else:
                con_list.append(i)

In [31]:
df_list = [income,arrhy,htru,blastchar,shopper,shrutime]
df_con_list = [income_con_col,arrhy_con_col,htru_con_col,blast_con_col,shopper_con_col,shrutime_con_col]
df_cat_list = [income_cat_col,arrhy_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,shrutime_cat_col]
for i in range(len(df_list)):
    con_cat(df_list[i],df_con_list[i],df_cat_list[i])

In [32]:
bio_con_col = list(bio.drop(['y'],axis=1).columns)
spam_con_col = list(spam.drop(['y'],axis=1).columns)

In [33]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: category_encoders in /usr/local/lib/python3.8/dist-packages (2.5.1.post0)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.3.5)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (0.12.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.21.6)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.7.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.5->category_encoders) (2022.7)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)

# Problem 1

In [34]:
import category_encoders as ce
def onehot(dataframe,cat_col):
    for col in cat_col:
        encoder = ce.OneHotEncoder(cols= [col])
        dfbin = encoder.fit_transform(dataframe[col])
        dataframe = pd.concat([dataframe,dfbin],axis = 1)
    dataframe = dataframe.drop(columns = cat_col)
    return dataframe

In [35]:
import warnings
warnings.filterwarnings("ignore")

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score,f1_score
scaler = StandardScaler()
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)
def problem1(clf,dataframe,judge,name,cat_col,con_col):
    dataframe = onehot(dataframe,cat_col)
    X = dataframe.drop(['y'],axis=1)
    y = dataframe['y']
    f1_list = []
    auc_list = []
    for train_index, valid_index in kf.split(X,y):
        train_x,valid_x = X.iloc[train_index],X.iloc[valid_index]
        train_y, valid_y = y.iloc[train_index],y.iloc[valid_index]
        if (judge ==1 and len(con_col) > 0):
            
            for col  in con_col:
                scaler.fit(train_x[[col]].values)
                train_x[['scale' + str(col)]] = scaler.transform(train_x[[col]].values)
                valid_x[['scale' + str(col)]] = scaler.transform(valid_x[[col]].values)
            train_x = train_x.drop(columns = con_col)
            valid_x = valid_x.drop(columns = con_col)
            
        clf.fit(train_x,train_y)
        predictions = clf.predict(valid_x)
        f1 = f1_score(valid_y, predictions)
        auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
        f1_list.append(f1)
        auc_list.append(auc_score)
    #print(name + " auc score: ",round(sum(auc_list)/5,4))
    print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [36]:
import lightgbm as lgb
whole_df_list = [income,arrhy,bank,htru,blastchar,shopper,bio,shrutime,spam,default]
name_list = ['income','arrhy','bank','htru','blastchar','shopper','bio','shrutime','spam','default']
whole_cat_list = [income_cat_col,arrhy_cat_col,bank_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,bio_cat_col,shrutime_cat_col,spam_cat_col,default_cat_col]
whole_col_list = [income_con_col,arrhy_con_col,bank_con_col,htru_con_col,blast_con_col,shopper_con_col,bio_con_col,shrutime_con_col,spam_con_col,default_con_col]
for i in range(len(whole_df_list)):
    problem1(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],0,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.715
arrhy f1 score:  0.5962
bank f1 score:  0.561
htru f1 score:  0.884
blastchar f1 score:  0.5822
shopper f1 score:  0.6542
bio f1 score:  0.7953
shrutime f1 score:  0.5946
spam f1 score:  0.9444
default f1 score:  0.48

In [96]:
for i in range(len(whole_df_list)):
    problem1(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.7147
arrhy f1 score:  0.5743
bank f1 score:  0.5616
htru f1 score:  0.8821
blastchar f1 score:  0.5726
shopper f1 score:  0.6564
bio f1 score:  0.7914
shrutime f1 score:  0.5929
spam f1 score:  0.9443
default f1 score:  0.4803

In [95]:
for i in range(len(whole_df_list)):
    problem1(LogisticRegression(),whole_df_list[i],0,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.3831
arrhy f1 score:  0.5074
bank f1 score:  0.3172
htru f1 score:  0.8746
blastchar f1 score:  0.5921
shopper f1 score:  0.4982
bio f1 score:  0.8003
shrutime f1 score:  0.0992
spam f1 score:  0.9038
default f1 score:  0.0006

In [38]:
from sklearn.linear_model import LogisticRegression
for i in range(len(whole_df_list)):
    problem1(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6623
arrhy f1 score:  0.4981
bank f1 score:  0.4508
htru f1 score:  0.8749
blastchar f1 score:  0.597
shopper f1 score:  0.5042
bio f1 score:  0.813
shrutime f1 score:  0.3138
spam f1 score:  0.9027
default f1 score:  0.467

# Problem 3

In [50]:
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)
def problem3_5bin(clf,dataframe,judge,name,cat_col,con_col):
    dataframe = onehot(dataframe,cat_col)
    X = dataframe.drop(['y'],axis=1)
    y = dataframe['y']
    f1_list = []
    auc_list = []
    for train_index, valid_index in kf.split(X,y):
        train_x,valid_x = X.iloc[train_index],X.iloc[valid_index]
        train_y,valid_y = y.iloc[train_index],y.iloc[valid_index]
        if (judge ==1 and len(con_col) > 0):
            for col  in con_col:
                mm_range = train_x[col].max() - train_x[col].min()
                min_value = int(np.floor(train_x[col].min()))
                max_value = int(np.ceil(train_x[col].max()))
                # bin=5
                inter_width = int(np.round(mm_range/5))
                if inter_width != 0:
                  intervals = [i for i in range(min_value, max_value+inter_width, inter_width)]
                  train_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=train_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
                  valid_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=valid_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
            train_x = train_x.drop(columns = con_col)
            valid_x = valid_x.drop(columns = con_col)
            
        clf.fit(train_x,train_y)
        predictions = clf.predict(valid_x)
        f1 = f1_score(valid_y, predictions)
        auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
        f1_list.append(f1)
        auc_list.append(auc_score)
    #print(name + " auc score: ",round(sum(auc_list)/5,4))
    print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [52]:
import lightgbm as lgb

whole_df_list = [income,arrhy,bank,htru,blastchar,shopper,bio,shrutime,spam,default]
name_list = ['income','arrhy','bank','htru','blastchar','shopper','bio','shrutime','spam','default']
whole_cat_list = [income_cat_col,arrhy_cat_col,bank_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,bio_cat_col,shrutime_cat_col,spam_cat_col,default_cat_col]
whole_col_list = [income_con_col,arrhy_con_col,bank_con_col,htru_con_col,blast_con_col,shopper_con_col,bio_con_col,shrutime_con_col,spam_con_col,default_con_col]
# LGBM
print('LGBM:')
for i in range(len(whole_df_list)):
    problem3_5bin(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])
# LR
print('LR:')
for i in range(len(whole_df_list)):
    problem3_5bin(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

LGBM:
income f1 score:  0.6592
arrhy f1 score:  0.4669
bank f1 score:  0.4276
htru f1 score:  0.8246
blastchar f1 score:  0.5816
shopper f1 score:  0.2062
bio f1 score:  0.7265
shrutime f1 score:  0.424
spam f1 score:  0.6338
default f1 score:  0.4779
LR:
income f1 score:  0.6289
arrhy f1 score:  0.473
bank f1 score:  0.3572
htru f1 score:  0.814
blastchar f1 score:  0.5918
shopper f1 score:  0.1738
bio f1 score:  0.6885
shrutime f1 score:  0.3104
spam f1 score:  0.6138
default f1 score:  0.4677

In [39]:
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)
def problem3_10bin(clf,dataframe,judge,name,cat_col,con_col):
    dataframe = onehot(dataframe,cat_col)
    X = dataframe.drop(['y'],axis=1)
    y = dataframe['y']
    f1_list = []
    auc_list = []
    for train_index, valid_index in kf.split(X,y):
        train_x,valid_x = X.iloc[train_index],X.iloc[valid_index]
        train_y,valid_y = y.iloc[train_index],y.iloc[valid_index]
        if (judge ==1 and len(con_col) > 0):
            for col  in con_col:
                mm_range = train_x[col].max() - train_x[col].min()
                min_value = int(np.floor(train_x[col].min()))
                max_value = int(np.ceil(train_x[col].max()))
                # bin=10
                inter_width = int(np.round(mm_range/10))
                if inter_width != 0:
                  intervals = [i for i in range(min_value, max_value+inter_width, inter_width)]
                  train_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=train_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
                  valid_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=valid_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
            train_x = train_x.drop(columns = con_col)
            valid_x = valid_x.drop(columns = con_col)
            
        clf.fit(train_x,train_y)
        predictions = clf.predict(valid_x)
        f1 = f1_score(valid_y, predictions)
        auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
        f1_list.append(f1)
        auc_list.append(auc_score)
    #print(name + " auc score: ",round(sum(auc_list)/5,4))
    print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [40]:
import lightgbm as lgb

whole_df_list = [income,arrhy,bank,htru,blastchar,shopper,bio,shrutime,spam,default]
name_list = ['income','arrhy','bank','htru','blastchar','shopper','bio','shrutime','spam','default']
whole_cat_list = [income_cat_col,arrhy_cat_col,bank_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,bio_cat_col,shrutime_cat_col,spam_cat_col,default_cat_col]
whole_col_list = [income_con_col,arrhy_con_col,bank_con_col,htru_con_col,blast_con_col,shopper_con_col,bio_con_col,shrutime_con_col,spam_con_col,default_con_col]
# LGBM
print('LGBM:')
for i in range(len(whole_df_list)):
    problem3_10bin(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])
# LR
print('LR:')
for i in range(len(whole_df_list)):
    problem3_10bin(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

LGBM:
income f1 score:  0.6737
arrhy f1 score:  0.4019
bank f1 score:  0.4757
htru f1 score:  0.8735
blastchar f1 score:  0.5841
shopper f1 score:  0.425
bio f1 score:  0.7538
shrutime f1 score:  0.4008
spam f1 score:  0.7799
default f1 score:  0.4746
LR:
income f1 score:  0.6455
arrhy f1 score:  0.4609
bank f1 score:  0.4074
htru f1 score:  0.8554
blastchar f1 score:  0.5951
shopper f1 score:  0.3681
bio f1 score:  0.7408
shrutime f1 score:  0.1944
spam f1 score:  0.7352
default f1 score:  0.4684

In [48]:
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)
def problem3_15bin(clf,dataframe,judge,name,cat_col,con_col):
    dataframe = onehot(dataframe,cat_col)
    X = dataframe.drop(['y'],axis=1)
    y = dataframe['y']
    f1_list = []
    auc_list = []
    for train_index, valid_index in kf.split(X,y):
        train_x,valid_x = X.iloc[train_index],X.iloc[valid_index]
        train_y,valid_y = y.iloc[train_index],y.iloc[valid_index]
        if (judge ==1 and len(con_col) > 0):
            for col  in con_col:
                mm_range = train_x[col].max() - train_x[col].min()
                min_value = int(np.floor(train_x[col].min()))
                max_value = int(np.ceil(train_x[col].max()))
                # bin=15
                inter_width = int(np.round(mm_range/15))
                if inter_width != 0:
                  intervals = [i for i in range(min_value, max_value+inter_width, inter_width)]
                  train_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=train_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
                  valid_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=valid_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
            train_x = train_x.drop(columns = con_col)
            valid_x = valid_x.drop(columns = con_col)
            
        clf.fit(train_x,train_y)
        predictions = clf.predict(valid_x)
        f1 = f1_score(valid_y, predictions)
        auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
        f1_list.append(f1)
        auc_list.append(auc_score)
    #print(name + " auc score: ",round(sum(auc_list)/5,4))
    print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [47]:
import lightgbm as lgb

whole_df_list = [income,arrhy,bank,htru,blastchar,shopper,bio,shrutime,spam,default]
name_list = ['income','arrhy','bank','htru','blastchar','shopper','bio','shrutime','spam','default']
whole_cat_list = [income_cat_col,arrhy_cat_col,bank_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,bio_cat_col,shrutime_cat_col,spam_cat_col,default_cat_col]
whole_col_list = [income_con_col,arrhy_con_col,bank_con_col,htru_con_col,blast_con_col,shopper_con_col,bio_con_col,shrutime_con_col,spam_con_col,default_con_col]
# LGBM
print('LGBM:')
for i in range(len(whole_df_list)):
    problem3_15bin(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])
# LR
print('LR:')
for i in range(len(whole_df_list)):
    problem3_15bin(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

LGBM:
income f1 score:  0.6893
arrhy f1 score:  0.4064
bank f1 score:  0.5024
htru f1 score:  0.8759
blastchar f1 score:  0.5715
shopper f1 score:  0.5131
bio f1 score:  0.7473
shrutime f1 score:  0.4115
spam f1 score:  0.8009
default f1 score:  0.4723
LR:
income f1 score:  0.6631
arrhy f1 score:  0.3946
bank f1 score:  0.4283
htru f1 score:  0.8591
blastchar f1 score:  0.5928
shopper f1 score:  0.4076
bio f1 score:  0.7393
shrutime f1 score:  0.1867
spam f1 score:  0.7714
default f1 score:  0.4668

In [90]:
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)
def problem3_20bin(clf,dataframe,judge,name,cat_col,con_col):
    dataframe = onehot(dataframe,cat_col)
    X = dataframe.drop(['y'],axis=1)
    y = dataframe['y']
    f1_list = []
    auc_list = []
    for train_index, valid_index in kf.split(X,y):
        train_x,valid_x = X.iloc[train_index],X.iloc[valid_index]
        train_y,valid_y = y.iloc[train_index],y.iloc[valid_index]
        if (judge ==1 and len(con_col) > 0):
            for col  in con_col:
                mm_range = train_x[col].max() - train_x[col].min()
                min_value = int(np.floor(train_x[col].min()))
                max_value = int(np.ceil(train_x[col].max()))
                # bin=20
                inter_width = int(np.round(mm_range/20))
                if inter_width != 0:
                  intervals = [i for i in range(min_value, max_value+inter_width, inter_width)]
                  train_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=train_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
                  valid_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=valid_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
            train_x = train_x.drop(columns = con_col)
            valid_x = valid_x.drop(columns = con_col)
            
        clf.fit(train_x,train_y)
        predictions = clf.predict(valid_x)
        f1 = f1_score(valid_y, predictions)
        auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
        f1_list.append(f1)
        auc_list.append(auc_score)
    #print(name + " auc score: ",round(sum(auc_list)/5,4))
    print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [97]:
import lightgbm as lgb

whole_df_list = [income,arrhy,bank,htru,blastchar,shopper,bio,shrutime,spam,default]
name_list = ['income','arrhy','bank','htru','blastchar','shopper','bio','shrutime','spam','default']
whole_cat_list = [income_cat_col,arrhy_cat_col,bank_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,bio_cat_col,shrutime_cat_col,spam_cat_col,default_cat_col]
whole_col_list = [income_con_col,arrhy_con_col,bank_con_col,htru_con_col,blast_con_col,shopper_con_col,bio_con_col,shrutime_con_col,spam_con_col,default_con_col]
# LGBM
print('LGBM:')
for i in range(len(whole_df_list)):
    problem3_20bin(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])
# LR
print('LR:')
for i in range(len(whole_df_list)):
    problem3_20bin(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

LGBM:
income f1 score:  0.6965
arrhy f1 score:  0.4514
bank f1 score:  0.5191
htru f1 score:  0.8596
blastchar f1 score:  0.5779
shopper f1 score:  0.5512
bio f1 score:  0.711
shrutime f1 score:  0.4013
spam f1 score:  0.7847
default f1 score:  0.4747
LR:
income f1 score:  0.664
arrhy f1 score:  0.39
bank f1 score:  0.4429
htru f1 score:  0.8403
blastchar f1 score:  0.5968
shopper f1 score:  0.4419
bio f1 score:  0.6825
shrutime f1 score:  0.1881
spam f1 score:  0.7671
default f1 score:  0.4676

In [93]:
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)
def problem3_50bin(clf,dataframe,judge,name,cat_col,con_col):
    dataframe = onehot(dataframe,cat_col)
    X = dataframe.drop(['y'],axis=1)
    y = dataframe['y']
    f1_list = []
    auc_list = []
    for train_index, valid_index in kf.split(X,y):
        train_x,valid_x = X.iloc[train_index],X.iloc[valid_index]
        train_y,valid_y = y.iloc[train_index],y.iloc[valid_index]
        if (judge ==1 and len(con_col) > 0):
            for col  in con_col:
                mm_range = train_x[col].max() - train_x[col].min()
                min_value = int(np.floor(train_x[col].min()))
                max_value = int(np.ceil(train_x[col].max()))
                # bin=20
                inter_width = int(np.round(mm_range/50))
                if inter_width != 0:
                  intervals = [i for i in range(min_value, max_value+inter_width, inter_width)]
                  train_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=train_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
                  valid_x[['binning' + str(col)]] = pd.DataFrame(pd.cut(x=valid_x[col],bins=intervals,include_lowest=True,labels=list(range(1,len(intervals)))))
            train_x = train_x.drop(columns = con_col)
            valid_x = valid_x.drop(columns = con_col)
            
        clf.fit(train_x,train_y)
        predictions = clf.predict(valid_x)
        f1 = f1_score(valid_y, predictions)
        auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
        f1_list.append(f1)
        auc_list.append(auc_score)
    #print(name + " auc score: ",round(sum(auc_list)/5,4))
    print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [98]:
import lightgbm as lgb

whole_df_list = [income,arrhy,bank,htru,blastchar,shopper,bio,shrutime,spam,default]
name_list = ['income','arrhy','bank','htru','blastchar','shopper','bio','shrutime','spam','default']
whole_cat_list = [income_cat_col,arrhy_cat_col,bank_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,bio_cat_col,shrutime_cat_col,spam_cat_col,default_cat_col]
whole_col_list = [income_con_col,arrhy_con_col,bank_con_col,htru_con_col,blast_con_col,shopper_con_col,bio_con_col,shrutime_con_col,spam_con_col,default_con_col]
# LGBM
print('LGBM:')
for i in range(len(whole_df_list)):
    problem3_50bin(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])
# LR
print('LR:')
for i in range(len(whole_df_list)):
    problem3_50bin(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

LGBM:
income f1 score:  0.6925
arrhy f1 score:  0.3371
bank f1 score:  0.5363
htru f1 score:  0.861
blastchar f1 score:  0.561
shopper f1 score:  0.6163
bio f1 score:  0.6072
shrutime f1 score:  0.3925
spam f1 score:  0.556
default f1 score:  0.4681
LR:
income f1 score:  0.6608
arrhy f1 score:  0.4018
bank f1 score:  0.4486
htru f1 score:  0.8463
blastchar f1 score:  0.5978
shopper f1 score:  0.4843
bio f1 score:  0.6201
shrutime f1 score:  0.1909
spam f1 score:  0.4169
default f1 score:  0.4658

# Problem 4

In [76]:
import category_encoders as ce

def onehot(dataframe,cat_col):
    for col in cat_col:
        encoder = ce.OneHotEncoder(cols= [col])
        dfbin = encoder.fit_transform(dataframe[col])
        dataframe = pd.concat([dataframe,dfbin],axis = 1)
    dataframe = dataframe.drop(columns = cat_col)
    return dataframe

# def label_encode(dataframe,cat_col):
#     for col in cat_col:
#         encoder = ce.OrdinalEncoder(cols= [col])
#         dfbin = encoder.fit_transform(dataframe[col])
#         dataframe = pd.concat([dataframe,dfbin],axis = 1)
#         print(dfbin)
#     dataframe = dataframe.drop(columns = cat_col)
#     return dataframe

def label_encode(dataframe,cat_col):
    for col in cat_col:
        encoder = ce.OrdinalEncoder(cols= [col])
        dataframe[col] = encoder.fit_transform(dataframe[col])
    return dataframe

def frequency_encode(dataframe,cat_col):
    for col in cat_col:
        encoder = ce.CountEncoder(cols= [col])
        dataframe[col] = encoder.fit_transform(dataframe[col])
    return dataframe

def target_encode(dataframe,cat_col,y):
    for col in cat_col:
        encoder = ce.TargetEncoder(cols= [col])
        dataframe[col] = encoder.fit_transform(dataframe[col],y)
    return dataframe

def betatarget_encode(dataframe,cat_col,y):
    for col in cat_col:
        encoder = ce.TargetEncoder(smoothing=10, cols= [col])
        dataframe[col] = encoder.fit_transform(dataframe[col],y)
    return dataframe

def leaveoneout_encode(dataframe,cat_col,y):
    for col in cat_col:
        encoder = ce.LeaveOneOutEncoder(cols= [col])
        dataframe[col] = encoder.fit_transform(dataframe[col],y)
    return dataframe

In [77]:
import warnings
warnings.filterwarnings("ignore")

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score,f1_score
scaler = StandardScaler()
cat_encode_list = [target_encode,betatarget_encode,leaveoneout_encode]
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)

def problem4(clf,dataframe,judge,name,cat_col,con_col):
    dataframe_use = dataframe.copy()
    for cat_encoder in cat_encode_list:

      X = dataframe.drop(['y'],axis=1)
      y = dataframe['y']
      f1_list = []
      auc_list = []
      for train_index, valid_index in kf.split(X,y):
          train_x, valid_x = X.iloc[train_index],X.iloc[valid_index]
          train_y, valid_y = y.iloc[train_index],y.iloc[valid_index]
          if (judge ==1 and len(con_col) > 0):
              train_x = cat_encoder(train_x,cat_col,train_y)
              valid_x = cat_encoder(valid_x,cat_col,valid_y)

              for col in con_col:
                  scaler.fit(train_x[[col]].values)
                  train_x[['scale' + str(col)]] = scaler.transform(train_x[[col]].values)
                  valid_x[['scale' + str(col)]] = scaler.transform(valid_x[[col]].values)
              train_x = train_x.drop(columns = con_col)
              valid_x = valid_x.drop(columns = con_col)
              
          clf.fit(train_x,train_y)
          predictions = clf.predict(valid_x)
          f1 = f1_score(valid_y, predictions)
          auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
          f1_list.append(f1)
          auc_list.append(auc_score)
          dataframe = dataframe_use
      #print(name + " auc score: ",round(sum(auc_list)/5,4))
      print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [78]:
whole_df_list = [income,arrhy,bank,htru,blastchar,shopper,bio,shrutime,spam,default]
name_list = ['income','arrhy','bank','htru','blastchar','shopper','bio','shrutime','spam','default']
whole_cat_list = [income_cat_col,arrhy_cat_col,bank_cat_col,htru_cat_col,blast_cat_col,shopper_cat_col,bio_cat_col,shrutime_cat_col,spam_cat_col,default_cat_col]
whole_col_list = [income_con_col,arrhy_con_col,bank_con_col,htru_con_col,blast_con_col,shopper_con_col,bio_con_col,shrutime_con_col,spam_con_col,default_con_col]

In [67]:
income

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,y
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

In [79]:
from sklearn.ensemble import RandomForestClassifier
for i in range(len(whole_df_list)):
    problem4(RandomForestClassifier(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6801
income f1 score:  0.6809
income f1 score:  0.2767
arrhy f1 score:  0.6465
arrhy f1 score:  0.6334
arrhy f1 score:  0.6035
bank f1 score:  0.5214
bank f1 score:  0.5211
bank f1 score:  0.0729
htru f1 score:  0.8843
htru f1 score:  0.8835
htru f1 score:  0.8843
blastchar f1 score:  0.5571
blastchar f1 score:  0.5554
blastchar f1 score:  0.1886
shopper f1 score:  0.6434
shopper f1 score:  0.6412
shopper f1 score:  0.2402
bio f1 score:  0.7877
bio f1 score:  0.795
bio f1 score:  0.7921
shrutime f1 score:  0.5829
shrutime f1 score:  0.578
shrutime f1 score:  0.307
spam f1 score:  0.9377
spam f1 score:  0.9399
spam f1 score:  0.9423
default f1 score:  0.473
default f1 score:  0.473
default f1 score:  0.3146

In [80]:
import xgboost as xgb
for i in range(len(whole_df_list)):
    problem4(xgb.XGBClassifier(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6894
income f1 score:  0.6899
income f1 score:  0.3721
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
bank f1 score:  0.4988
bank f1 score:  0.4988
bank f1 score:  0.0913
htru f1 score:  0.8853
htru f1 score:  0.8853
htru f1 score:  0.8853
blastchar f1 score:  0.5851
blastchar f1 score:  0.5851
blastchar f1 score:  0.2837
shopper f1 score:  0.6475
shopper f1 score:  0.6475
shopper f1 score:  0.2279
bio f1 score:  0.7907
bio f1 score:  0.7907
bio f1 score:  0.7907
shrutime f1 score:  0.5812
shrutime f1 score:  0.5812
shrutime f1 score:  0.2966
spam f1 score:  0.9267
spam f1 score:  0.9267
spam f1 score:  0.9267
default f1 score:  0.4682
default f1 score:  0.4733
default f1 score:  0.305

In [81]:
import lightgbm as lgb
for i in range(len(whole_df_list)):
    problem4(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.7106
income f1 score:  0.7101
income f1 score:  0.3545
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
bank f1 score:  0.5539
bank f1 score:  0.5539
bank f1 score:  0.0913
htru f1 score:  0.8821
htru f1 score:  0.8821
htru f1 score:  0.8821
blastchar f1 score:  0.5764
blastchar f1 score:  0.5764
blastchar f1 score:  0.1117
shopper f1 score:  0.6409
shopper f1 score:  0.6409
shopper f1 score:  0.2279
bio f1 score:  0.7914
bio f1 score:  0.7914
bio f1 score:  0.7914
shrutime f1 score:  0.5887
shrutime f1 score:  0.5887
shrutime f1 score:  0.3069
spam f1 score:  0.9443
spam f1 score:  0.9443
spam f1 score:  0.9443
default f1 score:  0.4726
default f1 score:  0.4771
default f1 score:  0.3135

In [82]:
from sklearn.neural_network import MLPClassifier
for i in range(len(whole_df_list)):
    problem4(MLPClassifier(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6743
income f1 score:  0.6799
income f1 score:  0.6674
arrhy f1 score:  0.5089
arrhy f1 score:  0.5581
arrhy f1 score:  0.5664
bank f1 score:  0.521
bank f1 score:  0.5079
bank f1 score:  0.5157
htru f1 score:  0.8875
htru f1 score:  0.8825
htru f1 score:  0.8868
blastchar f1 score:  0.5963
blastchar f1 score:  0.5828
blastchar f1 score:  0.5827
shopper f1 score:  0.6414
shopper f1 score:  0.6262
shopper f1 score:  0.6258
bio f1 score:  0.8276
bio f1 score:  0.8349
bio f1 score:  0.8349
shrutime f1 score:  0.5734
shrutime f1 score:  0.5722
shrutime f1 score:  0.5742
spam f1 score:  0.9333
spam f1 score:  0.9348
spam f1 score:  0.9335
default f1 score:  0.4678
default f1 score:  0.4797
default f1 score:  0.4655

In [83]:
from sklearn.linear_model import LogisticRegression
for i in range(len(whole_df_list)):
    problem4(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6525
income f1 score:  0.6522
income f1 score:  0.6487
arrhy f1 score:  0.4981
arrhy f1 score:  0.4981
arrhy f1 score:  0.4981
bank f1 score:  0.4441
bank f1 score:  0.4441
bank f1 score:  0.438
htru f1 score:  0.8749
htru f1 score:  0.8749
htru f1 score:  0.8749
blastchar f1 score:  0.5997
blastchar f1 score:  0.5997
blastchar f1 score:  0.5943
shopper f1 score:  0.5011
shopper f1 score:  0.5011
shopper f1 score:  0.4994
bio f1 score:  0.813
bio f1 score:  0.813
bio f1 score:  0.813
shrutime f1 score:  0.3087
shrutime f1 score:  0.3087
shrutime f1 score:  0.3027
spam f1 score:  0.9027
spam f1 score:  0.9027
spam f1 score:  0.9027
default f1 score:  0.4635
default f1 score:  0.4621
default f1 score:  0.4602

In [84]:
import warnings
warnings.filterwarnings("ignore")

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score,f1_score
scaler = StandardScaler()
cat_encode_list = [onehot,label_encode,frequency_encode]
kf = StratifiedKFold(n_splits=5,random_state=0,shuffle=True)

def problem4(clf,dataframe,judge,name,cat_col,con_col):
    dataframe_use = dataframe.copy()
    for cat_encoder in cat_encode_list:
      dataframe = cat_encoder(dataframe,cat_col)
      X = dataframe.drop(['y'],axis=1)
      y = dataframe['y']
      f1_list = []
      auc_list = []
      for train_index, valid_index in kf.split(X,y):
          train_x,valid_x = X.iloc[train_index],X.iloc[valid_index]
          train_y, valid_y = y.iloc[train_index],y.iloc[valid_index]
          if (judge ==1 and len(con_col) > 0):
              
              for col  in con_col:
                  scaler.fit(train_x[[col]].values)
                  train_x[['scale' + str(col)]] = scaler.transform(train_x[[col]].values)
                  valid_x[['scale' + str(col)]] = scaler.transform(valid_x[[col]].values)
              train_x = train_x.drop(columns = con_col)
              valid_x = valid_x.drop(columns = con_col)
              
          clf.fit(train_x,train_y)
          predictions = clf.predict(valid_x)
          f1 = f1_score(valid_y, predictions)
          auc_score = roc_auc_score(valid_y, clf.predict_proba(valid_x)[:, 1])
          f1_list.append(f1)
          auc_list.append(auc_score)
          dataframe = dataframe_use
      #print(name + " auc score: ",round(sum(auc_list)/5,4))
      print(name + " f1 score: ",round(sum(f1_list)/5,4))

In [85]:
from sklearn.ensemble import RandomForestClassifier
for i in range(len(whole_df_list)):
    problem4(RandomForestClassifier(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.673
income f1 score:  0.6775
income f1 score:  0.6772
arrhy f1 score:  0.6206
arrhy f1 score:  0.62
arrhy f1 score:  0.6434
bank f1 score:  0.4973
bank f1 score:  0.5151
bank f1 score:  0.5244
htru f1 score:  0.8848
htru f1 score:  0.8856
htru f1 score:  0.8838
blastchar f1 score:  0.5411
blastchar f1 score:  0.5632
blastchar f1 score:  0.5604
shopper f1 score:  0.6464
shopper f1 score:  0.6466
shopper f1 score:  0.6436
bio f1 score:  0.7862
bio f1 score:  0.7885
bio f1 score:  0.7924
shrutime f1 score:  0.5742
shrutime f1 score:  0.5859
shrutime f1 score:  0.5727
spam f1 score:  0.9387
spam f1 score:  0.9391
spam f1 score:  0.9395
default f1 score:  0.4749
default f1 score:  0.4723
default f1 score:  0.4783

In [86]:
import xgboost as xgb
for i in range(len(whole_df_list)):
    problem4(xgb.XGBClassifier(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6778
income f1 score:  0.6692
income f1 score:  0.6846
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
bank f1 score:  0.479
bank f1 score:  0.4774
bank f1 score:  0.4908
htru f1 score:  0.8853
htru f1 score:  0.8853
htru f1 score:  0.8853
blastchar f1 score:  0.5838
blastchar f1 score:  0.5803
blastchar f1 score:  0.5841
shopper f1 score:  0.6668
shopper f1 score:  0.6596
shopper f1 score:  0.6575
bio f1 score:  0.7907
bio f1 score:  0.7907
bio f1 score:  0.7907
shrutime f1 score:  0.5799
shrutime f1 score:  0.582
shrutime f1 score:  0.5687
spam f1 score:  0.9267
spam f1 score:  0.9267
spam f1 score:  0.9267
default f1 score:  0.4654
default f1 score:  0.4685
default f1 score:  0.4738

In [87]:
import lightgbm as lgb
for i in range(len(whole_df_list)):
    problem4(lgb.LGBMClassifier(application = 'binary'),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.7147
income f1 score:  0.7124
income f1 score:  0.7138
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
arrhy f1 score:  0.5743
bank f1 score:  0.5616
bank f1 score:  0.5598
bank f1 score:  0.5631
htru f1 score:  0.8821
htru f1 score:  0.8821
htru f1 score:  0.8821
blastchar f1 score:  0.5726
blastchar f1 score:  0.5775
blastchar f1 score:  0.5771
shopper f1 score:  0.6564
shopper f1 score:  0.6481
shopper f1 score:  0.6507
bio f1 score:  0.7914
bio f1 score:  0.7914
bio f1 score:  0.7914
shrutime f1 score:  0.5929
shrutime f1 score:  0.589
shrutime f1 score:  0.5941
spam f1 score:  0.9443
spam f1 score:  0.9443
spam f1 score:  0.9443
default f1 score:  0.4803
default f1 score:  0.4805
default f1 score:  0.479

In [88]:
from sklearn.neural_network import MLPClassifier
for i in range(len(whole_df_list)):
    problem4(MLPClassifier(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6628
income f1 score:  0.6602
income f1 score:  0.3338
arrhy f1 score:  0.505
arrhy f1 score:  0.548
arrhy f1 score:  0.554
bank f1 score:  0.5432
bank f1 score:  0.4996
bank f1 score:  0.3399
htru f1 score:  0.8858
htru f1 score:  0.8864
htru f1 score:  0.882
blastchar f1 score:  0.5794
blastchar f1 score:  0.5746
blastchar f1 score:  0.3398
shopper f1 score:  0.6331
shopper f1 score:  0.6302
shopper f1 score:  0.3364
bio f1 score:  0.8216
bio f1 score:  0.8224
bio f1 score:  0.8297
shrutime f1 score:  0.5791
shrutime f1 score:  0.5783
shrutime f1 score:  0.359
spam f1 score:  0.9346
spam f1 score:  0.9354
spam f1 score:  0.9368
default f1 score:  0.4601
default f1 score:  0.4622
default f1 score:  0.2872

In [89]:
from sklearn.linear_model import LogisticRegression
for i in range(len(whole_df_list)):
    problem4(LogisticRegression(),whole_df_list[i],1,name_list[i],whole_cat_list[i],whole_col_list[i])

income f1 score:  0.6623
income f1 score:  0.5521
income f1 score:  0.4853
arrhy f1 score:  0.4981
arrhy f1 score:  0.4981
arrhy f1 score:  0.4981
bank f1 score:  0.4508
bank f1 score:  0.4125
bank f1 score:  0.1881
htru f1 score:  0.8749
htru f1 score:  0.8749
htru f1 score:  0.8749
blastchar f1 score:  0.597
blastchar f1 score:  0.5949
blastchar f1 score:  0.5678
shopper f1 score:  0.5042
shopper f1 score:  0.4869
shopper f1 score:  0.5223
bio f1 score:  0.813
bio f1 score:  0.813
bio f1 score:  0.813
shrutime f1 score:  0.3138
shrutime f1 score:  0.3093
shrutime f1 score:  0.2519
spam f1 score:  0.9027
spam f1 score:  0.9027
spam f1 score:  0.9027
default f1 score:  0.467
default f1 score:  0.2869
default f1 score:  0.1483